#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod 'stdlib',
  :git => 'git://github.com/puppetlabs/puppetlabs-stdlib.git'

mod 'mysql',
  :git => 'git://github.com/puppetlabs/puppetlabs-mysql.git'

mod 'apt',
  :git => 'git://github.com/puppetlabs/puppetlabs-apt.git'

mod 'concat',
  :git => 'git://github.com/puppetlabs/puppetlabs-concat.git'

mod 'nodejs',
  :git => 'git://github.com/puppetlabs/puppetlabs-nodejs.git'

mod 'archive',
  :git => 'git://github.com/camptocamp/puppet-archive.git'
